spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true

info:
  app:
    name: apiGateway
    description: FounderLink Gateway Server
    version: 1.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    enabled: true
