spring:
  datasource:
    url: ${MESSAGING_DB_URL}
    username: ${MESSAGING_DB_USERNAME}
    password: ${MESSAGING_DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
